import type { User } from '@/types';

export const users: User[] = [
  {
    id: 'u1',
    name: 'Aarav Singh',
    email: 'aarav@iitg.ac.in',
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Aarav',
    verified: true,
    cScore: 4.8,
    isHost: true,
    bio: 'Photographer and mountain lover. I host relaxed trips for people who like slow mornings.',
    interests: 'Photography, Trekking, Coffee',
    memberSince: 'Jan 2024',
    genome: { reliability: 0.9, flexibility: 0.6, fun: 0.8, safety: 0.9, contribution: 0.7 },
  },
  {
    id: 'u2',
    name: 'Sukhjot Singh',
    email: 'sukhjot@iitg.ac.in',
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Sukhjot',
    verified: true,
    cScore: 4.2,
    isHost: false,
    bio: 'Always up for an adventure. Captain of the Guwahati Crew.',
    interests: 'Roadtrips, Music, Food',
    memberSince: 'Feb 2024',
    genome: { reliability: 0.7, flexibility: 0.8, fun: 0.9, safety: 0.6, contribution: 0.7 },
  },
  {
    id: 'u3',
    name: 'Aman Kumar',
    email: 'aman@iitg.ac.in',
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Aman',
    verified: true,
    cScore: 4.0,
    isHost: false,
    bio: 'Backpacker on a budget. Good with maps and bad with sleep schedules.',
    interests: 'Backpacking, Maps, Sunsets',
    memberSince: 'Mar 2024',
    genome: { reliability: 0.6, flexibility: 0.7, fun: 0.8, safety: 0.7, contribution: 0.6 },
  },
  {
    id: 'u4',
    name: 'Priya Mehta',
    email: 'priya@iitg.ac.in',
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Priya',
    verified: true,
    cScore: 4.5,
    isHost: false,
    bio: 'Planner at heart. I carry the first-aid kit and the snacks.',
    interests: 'Planning, Hiking, Baking',
    memberSince: 'Jan 2024',
    genome: { reliability: 0.8, flexibility: 0.9, fun: 0.9, safety: 0.8, contribution: 0.8 },
  },
  {
    id: 'u5',
    name: 'Ravi Sharma',
    email: 'ravi@iitg.ac.in',
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Ravi',
    verified: false,
    cScore: 3.8,
    isHost: false,
    bio: 'New to this. Excited to join my first crew.',
    interests: 'Roadtrips, Gaming',
    memberSince: 'Jun 2024',
    genome: { reliability: 0.5, flexibility: 0.6, fun: 0.7, safety: 0.5, contribution: 0.6 },
  },
  {
    id: 'u6',
    name: 'Neha Patel',
    email: 'neha@iitg.ac.in',
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Neha',
    verified: true,
    cScore: 4.3,
    isHost: false,
    bio: 'Solo traveller turned squad captain. I like quiet trails and loud laughs.',
    interests: 'Solo travel, Reading, Tea',
    memberSince: 'Feb 2024',
    genome: { reliability: 0.7, flexibility: 0.8, fun: 0.8, safety: 0.7, contribution: 0.7 },
  },
];

export const currentUser = users[1];

export const getUserById = (id: string): User | undefined => users.find((u) => u.id === id);
