import type { AppNotification } from '@/types';

export const notifications: AppNotification[] = [
  {
    id: 'n1',
    type: 'offer_received',
    title: 'Offer from Aarav',
    body: 'Your squad was offered a spot on the Meghalaya Circuit! 12h left to confirm.',
    data: { tripId: 't1', squadId: 's1' },
    isRead: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n2',
    type: 'request_approved',
    title: 'Request approved!',
    body: 'Aarav approved your request to join Tunjang Peak Trek.',
    data: { tripId: 't2' },
    isRead: true,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n3',
    type: 'request_rejected',
    title: 'Request rejected',
    body: 'Neha rejected your request for the Sunderbans Boat Trail.',
    data: { tripId: 't5' },
    isRead: false,
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n4',
    type: 'trip_edited',
    title: 'Trip details changed',
    body: 'Aarav updated the itinerary for Spiti Valley Circuit.',
    data: { tripId: 't6' },
    isRead: true,
    created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n5',
    type: 'review_prompt',
    title: 'Rate your crew',
    body: 'Your Coorg Staycation ended. Leave reviews for your squad to unlock new applications.',
    data: { tripId: 't4' },
    isRead: false,
    created_at: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n6',
    type: 'offer_received',
    title: 'Offer from Neha',
    body: 'Solo Travellers was offered a spot on the Sunderbans Boat Trail! 20h left.',
    data: { tripId: 't5', squadId: 's3' },
    isRead: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n7',
    type: 'request_approved',
    title: 'Request approved!',
    body: 'Neha approved your request to join the Roadtrip to Shillong.',
    data: { tripId: 't3' },
    isRead: true,
    created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n8',
    type: 'trip_edited',
    title: 'Budget updated',
    body: 'Aarav updated the budget for the Meghalaya Circuit.',
    data: { tripId: 't1' },
    isRead: true,
    created_at: new Date(Date.now() - 70 * 60 * 60 * 1000).toISOString(),
  },
];
